default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_api_development

test:
  <<: *default
  database: blog_api_test

production:
  <<: *default
  database: blog_api_production
  username: blog_api
  password: <%= ENV["BLOG_API_DATABASE_PASSWORD"] %>
